### ISSUE TITLE
What Are The Fundamental Non-Technical Skills Everyone Should Master? 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#178]
In **Cal Newport**'s book "_**So Good They Can't Ignore You**. Why **skills** trump passion in the quest for work you love_", he describes the need to acquire/accumulate "valuable skills" and "career capital" ***`before`*** we _can_ find work we _love_ doing. 

Cal makes a _compelling_ evidence-based case why _most_ people _fail_ at "following their passion" or "doing what they love". People _fail_ to find work they love, or to make a _living_ doing that work, because they fail to develop the _skills_ necessary to make their output _valuable_ to the world. 
i.e. _if you don't have the skills, you won't pay the bills!_ 

[![image](https://user-images.githubusercontent.com/194400/48599754-003e9100-e961-11e8-918d-69dadfd76bd1.png)](https://youtu.be/99v9-4uk9ZQ)

+ So Good Book (8 hours): https://www.amazon.com/Good-They-Cant-Ignore-You/dp/1455509124
+ Visual Summary (8 mins): https://youtu.be/DFjTD8v7xuw
+ Talks at Google (40 mins): https://youtu.be/qwOdU02SE0w

That got us thinking: what are highly useful (_and valuable_) skills that _anyone_ can learn/master
that do _not_ require writing _any_ **`code`** which will help people find work they _love_ doing?

What are the "core" non-technical skills that _everyone_ should master regardless of what they do for a living? What are skills that if mastered have a _significant_ impact on your life in both the short, medium and _long_ term? Here are the "Top Ten" that come to _my_ mind:

+ [ ] ***Focus*** - being able to focus your attention on **_one_ thing** at time without requiring external stimulus. This might sound "_simple_" but it's _surprisingly_ rare! 
  Further Reading:
  + [ ] https://jamesclear.com/multitasking-myth

+ [ ] ***Listening*** - if you are unable to _listen_ to what someone else is saying you have [fallen at the first hurdle](https://idioms.thefreedictionary.com/fall+at+the+first+hurdle). This is _related_ to **Focus**; you cannot have listening skills without focus.
> _Obviously_ this is only relevant to people who are not hearing-impaired. 👂 

+ [ ] ***Empathy*** - _understanding_ how someone `else` is feeling and being aware that their emotional state is almost _certainly_ not _identical_ to your own. Studying "***emotional intelligence***" is one of the best time-investments you can make, _especially_ if you already have other types of intelligence and are struggling to _understand_ why people don't "_like_" you!

+ [ ] **Reading** - being able to read is a pretty fundamental skill to "modern life"; we take it for [_granite_](https://youtu.be/iXVJfRZTbyQ?t=15) that _everyone_ knows how to read, or that people are _effective_ at reading. 
  + [ ] **What _should_ I read**? Knowing _what_ to read and _when_ to read it and what _not_ to read. e.g: don't read mass-media news first thing in the morning, it will prime you for _negative bias_. Read something that moves you towards your goal or furthers your mission. 
  + [ ] **_Speed_ Reading**! How to rapidly process large blocks of text to _efficiently_ extract the information you _need_ without getting stuck reading hundreds of pages of irrelevant filler. Any "knowledge" work requires reading. From _email_ to _technical manuals_, _everyone_ needs to have the ability to "scan" through blocks of text and find the _specific sentence_ they are searching for.

+ [ ] **Writing** - writing on _paper_ is an _essential_ skill that few people focus on developing after they are _forced_ to write prescriptive and uninteresting essays/reports in school. Developing writing skills is relevant to almost _any_ work/job/career and it's _especially_ important to Entrepreneurs/Freelancers. If you want to achieve _anything_ in life, write about it! 
  Examples:
  + [tesla.com/en_GB/blog/secret-tesla-motors-master-plan-just-between-you-and-me](https://www.tesla.com/en_GB/blog/secret-tesla-motors-master-plan-just-between-you-and-me)
  + https://seths.blog/top-100
  + [paulgraham.com/articles.html](http://www.paulgraham.com/articles.html)
> "_Writing is nature's way of letting you know how sloppy your thinking is_." ~ [Dick Guindon](https://github.com/nelsonic/nelsonic.github.io/issues/521#issuecomment-436649498)

  + [ ] **Spelling** good spelling can be the difference between getting hired. I've _seen_ hiring managers/HR people _reject_ a CV because it had a spelling error on it. Their reasoning being that if the person does not have sufficient attention-to-detail in presenting _themself_, they are not going to be a good representative of the company ***and/or*** they won't be _excellent_ at doing their job.
A good "side effect" of lots of reading is that spelling is just pattern recognition, the more you practice reading and writing, the better you get and eventually spelling is like _breathing_.
But don't take it for granted! If you have had issues with spelling, find reading material you _enjoy_ and set aside the time to _read it_! If you need a "short term fix" for your spelling, consider Grammarly. But remember that tools like Grammarly are a "band aid" treating the symptom not addressing the ailment; you are _way_ better off putting in the work to develop the skills than trying to "shortcut" this!
> Personal note: Trust me, as a dyslexic, I know exactly what it's like to consistently miss-read and miss-spell words for all of my school life. It was _torture_! It was _all_ "stick" and no "carrot" in school! I'm _not_ suggesting that I now spell _every_ word perfectly, but since I started consistently reading, I have _largely_ overcome my spelling "disability". 📚+ 🤓+ ✍️ = ⭐️✅ 

+ [ ] **Touch Typing**! If you do _anything_ with a computer, being able to type _fast_ and _accurately_, is the difference between 
this has been _explicitly_ mentioned in the "start-here" README.md for the past few years: [https://github.com/dwyl/start-here#touch-typing](https://github.com/dwyl/start-here/tree/afcf6751ac05da0b296915231bdb20cee5525653#touch-typing)
![image](https://user-images.githubusercontent.com/194400/48600661-bb1c5e00-e964-11e8-8b49-7b9f70c4728d.png)
Touch-typing is one of the most _valuable_ skills a "knowledge worker" can have! It _multiplies_ your output because if you can _type_ as fast as you _think_ there is no "bottleneck" in communicating!
And yet, I still walk around _our_ office and see people two-finger typing and looking at their keyboards! 

+ [ ] **Arithmetic** - I _often_ see people reaching for a _calculator_ to do _simple_ arithmetic. 😕 
Or when discussing number for an idea, the look of _panic_ on their faces when they cannot multiply two numbers in their head. e.g: 32 x 256 ... (_8192 ..._) Being able to calculate this in _less_ time than it takes to (pull out a phone and) type the numbers into an App, is _fundamental_ to success in _life_. I'm not suggesting that it's _impossible_ to be "successful" without proficiency arithmetic. I'm _sure_ you can think of _examples_ of where people are "_successful_" _without_ knowing "math". But, trust me, I can show you _way_ more examples of people who, having _mastered_ the "basic" math skills have transformed their lives from poverty to _property_! Even if "_material wealth_" is not your focus/goal, having _food_ to eat _probably is_; and that is the _origin_ of Arithmetic! The modern systems of counting were _developed_ to count crops so that people could be fed. If you like food, learn Math!

+ [ ] **Memory** - practicing memory techniques is _incredibly_ valuable. Most people don't realise how much they rely on their memory to get _anything_ done. You just need to sit with a person who has a defective short-term memory (_either because of a neurological issue or simply lack of practice_) to realise how debilitating it is to _not_ have good working memory. _All_ memory techniques can be _learned_ and skills can be practiced. If people are _not_ doing the _daily_ practice, _why_ not? Is it because they don't realise that Memory == Intelligence? If you _want_ to be "_smarter_", pick up a book on Memory! If you want to _dramatically_ improve your cognitive abilities, read _all_ the books on Memory! (_we have the 10 best ones in dwyl's library! if you are remote and want to read a specific book, just show your interest!_)

+ [ ] **Reasoning** - how to think about something without being trapped by logical fallacies, influenced by special interested or led astray by charismatic (_manipulative_) people with negative agendas!  

What are _other_ skills _you_ think people should `master` that make them more effective in _life_?

**Comment by nelsonic** [comment]
+ Communication (we covered writing above, but speaking, knowing when to keep quiet! Drawing! Not gossiping or speaking badly about people who are not present.
+ Searching! You don’t need to be “technical” to know how to use a search engine!
+ Punctuality being on time is both easy and _essential_.
+ Organisation
+ Mindfulness
+ Sleep (_yes, Sleep is “skill” some people have **mastered** and others can **learn**_)
+ Diplomacy (a combination of listening, empathy and communication)
+ Financial literacy
+ Patience

**Comment by iteles** [comment]
❤️ 

With the addition of your bullet points in the second bullet point, this is a pretty comprehensive list. Communication more widely and financial literacy were the two that came to mind for me when reading your list.

I would add
+ Self-confidence/sense of self-worth
+ Goal-setting
+ Asking questions (this is a sub-topic of communication but I think important enough to stand on its own)

**Comment by YvesMuyaBenda** [comment]
I have thoughts about how to develop each and every one of those skills, but my recentresearch in movement, especially the work of the "movement specialist" Ido Portal, led me to a really good model of skill building (learning new physical movements is about as basic as learning gets; think of learning to walk).

Thus I would say that the meta-skill above all others is _knowing how to learn_ (first ten minutes generalizes to programming, especially learning how to solve coding probems): [How to Build Mathematical Intutition](https://www.youtube.com/watch?v=KAMTNCuADl4).

The original model of Ido Portal which relates to learning movements is _isolation, integration, improvisation_ (for example): [Three Magic Words]: http://wellroundedathlete.net/three-magic-words/

Using the model, allowed me to clarify in my mind how to compare different approaches to, say, touch-typing, and why the software I have seen _just does not quite do it for me_ (the model of learning the software is based upon is incomplete).

**Comment by YvesMuyaBenda** [comment]
Too, my interest in movement is wheras "knowing how to learn" is the basic meta-skill, the most basic skill for me is "knowing how to move". For example, touch-typing is essentially learning a basic set of movments, so too is learning how to speak a foreign language, so too playing a musical instrument, so too ...

The Movenat folk have quite a comprehensive list of basic general movement classified into categories. For example, here is a fundamenta list of movements: [15 Natural Movements Everyone Shouold Be Able to Do](https://www.movnat.com/doable-movements/).

This whole topic relates to "developer health" in the sense that a lot  of physical problems developers tend to develop (pun intented!!!) can be thought from the perspective of lack of movement, so problems like weight gain, lack of mobility, poor posture, wrist problems, muscle imbalances, weak spine, and lack of metabolic conditioning.

It is also said that learning new movements and physical activity in general are positively correlated to things such as improving short and long term memory, and the ability to focus, so ...

**Comment by YvesMuyaBenda** [comment]
Also @nelsonic: If a touch typing tutorial contained a library of common vocabulary (like books they give to school children) or allowed you to input a text file of something you like reading as source material, then one can accomplish two things at once: work on touch typing and improve spelling. 

The method would also likely be faster than just reading a lot, because if say, one had typing challenges compiled from the source material that one is reading, then the touch-typing would make a person pay much more attention to how the words are spelt, and too, they have the mind-hand connection to aid memory.

**Comment by nelsonic** [comment]
https://youtu.be/qe8gslqFUMw

**Comment by iteles** [comment]
https://www.youtube.com/watch?v=HLP7jEVIh8U

**Comment by nelsonic** [comment]
@iteles did you _intentionally_ share a [Jordan Peterson](https://github.com/nelsonic/nelsonic.github.io/issues/618#issuecomment-462959131) video...?

Best predictor of lifetime success is [conscientiousness](https://en.wikipedia.org/wiki/Conscientiousness). ✅

**Comment by iteles** [comment]
@nelsonic Yes! I didn't look into his background but so far I've heard the first 10 minutes of the video above (where he discusses conscientiousness) and found it pretty inspiring.

**Comment by nelsonic** [comment]
@iteles Yeah. I too do not _share_ Jordan's views on a few areas ... and feel that he is _undermining_ his "_core_" message by having/publicising _strong_ opinions on too many _controversial_  subjects. 😕
But then again, if he _feels_ strongly about those things and is taking a "stand", that's _better_ than keeping quiet and allowing those feelings to fester. That's kinda the point of "_free speech_"; to encourage civil debate on meaningful topics not shy away attempting to conform to ["PC"](https://youtu.be/tPEHbJgomgA?t=245) while still harbouring negativity.  

I can't think of anyone on any part of the political spectrum that would _disagree_ with his ["**12 Rules**"](https://github.com/nelsonic/nelsonic.github.io/issues/618#issuecomment-455466661) 💭 

I agree with _everything_ in the video you shared above. 
Conscientiousness, industriousness, micro habits, setup aims for yourself, situational analysis.
All fairly common sense. but as [Voltaire](https://www.goodreads.com/quotes/tag/common-sense) said: "_Common sense is not so common_.” 



> "_You're going to have to put some **effort** into your life_" ...
"_Develop a vision of what you would like your life to be_"
"_The question always is: Why do something? Cause doing nothing is easy, you just sit there and don't do anything; that's real easy. The question is why would you do anything? And the answer to that is that you've determined by some means that it's worthwhile_."
"_Often people won't specify their goals, because they don't like to specify conditions for failure_"
"_If you keep yourself all vague and foggy, which is real easy cause that's just a matter of not doing as well, then you don't know when you fail. And people might say, I don't want to know when I fail because that's painful, so I'll keep myself blind about when I fail. That's fine, except you'll fail all the time then! You just won't know it until you've failed so badly that you're done._"
"_[Willful blindness](https://en.wikipedia.org/wiki/Willful_blindness); you could have known, but you chose not to_."
"_A schedule can be unbelievably useful; make a damn schedule! And stick to it!_"
"_What's the right ratio of responsibility to reward?_"
"_You're a bad employee and a worse boss, you don't know what to do, and and when you tell yourself what to do, you don't do it anyway... so you should fire yourself and find someone else._"

> [10:05](https://youtu.be/HLP7jEVIh8U?t=605) "_You probably **waste** like **six hours a day**. I think we did an economic calculation about that a while back. Your time is probably worth about fifty bucks and hour ($50/h). You're not getting paid that now, but you're young so this is **investment time** and what you do now is going to multiply it's effects in the future. So let's say it's $50/h which is perfectly reasonable. So if you waste 6h/day, and you are, then you are wasting about $2,000/week or about $100,000/year. Go ahead, but that's what it's costing you. And you need to know what your damn time is worth!_"

> [11:18](https://youtu.be/HLP7jEVIh8U?t=678) Predictors of Performance:
> "_Outline a goal that you would actually like to hit._"

> "_You want to negotiate so that you don't walk away miserable and resentful, because that makes you hostile and then you'll work to hurt them._" 
> "_How about we walk away from our mutual negotiations thrilled_?"

> "_People who whine about being alive are dangerous to themselves an other people._"

> "_So you might think I can have what I want. You'd better well figure out what it is. And you can't just wait for the have what you want fairy to show up at your doorstep and grant it, because obviously that's not going to happen._"

> [14:53](https://youtu.be/HLP7jEVIh8U?t=893) "_Social Networking, that's another big deal. It's one of the advantages that older people have over younger people. When I go to one of them and say: 'can you do X?' or 'Do you know X?' they say: 'no, but I know someone who can'. And that's a huge advantage. So another thing you want to think about as you move through life is that use your ability to network properly. That doesn't mean 'shmooze' and impress people. It means you try to surround yourself with people who are competent in multiple different dimensions and you maintain your relationships with them. 
That's something extraverted people can be really good at._"
> [15:58](https://youtu.be/HLP7jEVIh8U?t=958) "_Consciously develop and maintain your social networks._"

> [16:05](https://youtu.be/HLP7jEVIh8U?t=965) "_Let's talk about friendships for a minute. Here's how you know if someone is your friend_: 
> (a) _you **can tell them bad news**, and they will listen. They won't tell you why you are stupid and why that bad thing happened to you and how something worse happened to them once ... and derail the whole conversation. You can actually tell them bad news and they'll listen._
> (b) _this is a weirder thing: you can tell them **good news** and they'll help you celebrate. And that's a really good way of deciding who you should have around you, because if you have someone around you and something good happens and you're afraid to even admit it because if you let that be known and it will certainly be taken away. If tell someone something good happened and they give you a whack and then talk about the great thing that happened to them 3 years ago. Or worse the great thing that happened to someone that they knew 3 years ago ... Go away from that person, they're not helpful to you. And they're not helpful to themselves either._"
> [17:10](https://youtu.be/HLP7jEVIh8U?t=1030) "_Surround yourself with the people who want the best for the best part of you._"
"_You can hang around with weasels who are trying to pull you down, to justify the fact that they are spiraling downhill aswell. The upside of that is that you don't have to have any responsibility and you can all whine about how retched life is. It's a bad medium to long-term plan._" 
>[17:34](https://youtu.be/HLP7jEVIh8U?t=1054) "_Surround yourself with people who are facilitating your development._" 
> "_if they don't pay any attention and they keep doing the same damn thing over and over and they are not going anywhere, then maybe the proper thing to do is say: 'you just have your misery, I'll go off and have my life. Maybe you'll wake up at some point in the future and thing that's a better way of being' ...  just putting up with it, they call that 'enabling'. You put up with that behaviour and you're providing ['tacit consent'](https://plato.stanford.edu/entries/locke-political) or even 'tacit approval'. It's a bad idea. You have the right and responsibility to surround yourself with the people who are good for the best part of you._"

> [18:45](https://youtu.be/HLP7jEVIh8U?t=1124) "_Skills that's another thing you can do if you want to increase your probability of success_."
"_Every time you have an opportunity to take an opportunity, that would provide you with a new skill, do it! Learn to program. Learn to write. Learn to read. Learn to read new things! Learn to public speak. Learn how to introduce yourself to people. Learn how to social network. Learn how to talk to your boss; talk about the problem and the **solution**._" 
> [19:37](https://youtu.be/HLP7jEVIh8U?t=1177) "_Don't be a problem for the people who want to give you money. That's a good rule of thumb. If someone wants to give you money, then **help them** do that! Do that by bringing them solutions. In part by developing your skills._"
> [20:03](https://youtu.be/HLP7jEVIh8U?t=1203) "_Take the opportunity if it will teach you something that you can use for other opportunities. 
Because even if it fails - which it probably will - it doesn't matter because you've accrued something of value that you can bring forward to the next situation._"

> [21:21](https://youtu.be/HLP7jEVIh8U?t=1281) "_Wealth constitutes what you have when someone takes all your money away_."
> "_The way that you build up that sort of wealth is you turn yourself into someone who is competent in multiple directions, and you can be doing that all the time._" 
> "_You can **learn anything** you want **whenever you want**._" 

All of this seems fairly obvious to me and helpful to _anyone_ who hasn't thought about it.

**Comment by YvesMuyaBenda** [comment]
Thinking--an essential non-tech skill everyone should master is thinking! I just spent the last couple of weeks contemplating what the act of thinking actually consists of, after wondering about it since childhood, and it occured to me, it has only been recently that the concept has become sharp.
As a child, I wondered why in the schools no one described the act of thinking so as to help children improve their minds while they were young, and soceity gave them the free time, and I now realise that ...

I have been doing wrong all this time!

Jordan Peterson -- it seems that many people need guidance, and from whom they seek it from is ... well ... up to them. If a person does not develop self-thinking, then the tendency is to follow folk who seem authoratative and have social cachet!

**Comment by YvesMuyaBenda** [comment]
As for any skill someone mentions, my first thoughts are always, what are the first few concrete steps in developing the skill, as in right now, and what are the ways one would observe how well the skill is being developed. Say, developing specific mental traits, such as thinking out well scoped out, well narrowed goals, whose resolutions are clear; in my mind is that a whole bunch of folk have tried to transport the mental habits of TDD into either earlier parts of the computer science/programming curriculum, or into other areas of life. If folk play games created to teach TDD would that improve the precision of their thoughts? Would they get in the mental habits of creating tests which specify what is wanted? Or from another point of view, are people who think in small steps, with well defined resolutions, and paths to resolutions, would they be the ones to easily learn TDD, by just learning the tools needed to implement it in whatever language?

**Comment by nelsonic** [comment]
Ask HN: What's the most valuable thing you can learn in an hour?
https://news.ycombinator.com/item?id=21581361
**Top Answer**: How to manage your money. 💰 [https://www.youtube.com/watch?v=bE8i-4HpKlM](https://www.youtube.com/watch?v=bE8i-4HpKlM&list=PLyl80QTKi0gPBcb32paMvXxcq7UUeJskV)
I tend to agree; this is the single most valuable thing anyone can do with an hour  and yet so few people take the time to master their finances and end up living "paycheck to paycheck" or _worse_ in perpetual dept. 😞

**Comment by nelsonic** [comment]
Skills Every Child Will Need to Succeed in 21st century (Dr. Laura A. Jana TEDx Talk): https://youtu.be/z_1Zv_ECy0g

**Comment by nelsonic** [comment]
https://skamille.medium.com/an-incomplete-list-of-skills-senior-engineers-need-beyond-coding-8ed4a521b29f

**Comment by nelsonic** [comment]
https://skamille.medium.com/an-incomplete-list-of-skills-senior-engineers-need-beyond-coding-8ed4a521b29f
via: https://news.ycombinator.com/item?id=27414443
