### ISSUE TITLE
Automatically Invite People who ⭐ this repo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#255]
At present we have zero automation for adding people to **`@dwyl`**. 🤖 

It means we end up with _lots_ of issues/comments in threads from people asking to join. 💬 
e.g: #143, #207, #209, #210, #211, #213, #214, #215, #216, #217, #218, #219, #220, #221, #223, #225, #231, #234, #237, #238, #239, #240, #250, #252, #254, etc ... 
https://github.com/dwyl/start-here/issues?q=is%3Aissue+invite
<img width="1067" alt="dwyl-invite-request" src="https://user-images.githubusercontent.com/194400/190618672-1326dcb8-5ab9-4970-93dc-affe1dc0c89f.png">

Each time someone requests to join we have to _manually_ add them and that takes time ... ⌛ 

# Todo

+ [ ] **_Update_ code** to log who has starred the repo
+ [ ] **Data** to be stored: 
  + [ ] Github **`username`**: `Fields.Encrypted`
  + [ ] **`repo_name`**
  + [ ] **`inserted_at`**

Once we are storing the data, we can write the code to:

+ [ ] **_Automate_ inviting** the people

**Comment by nelsonic** [comment]
Going to try and take a look at this once back in PT. ⏳ 
Not because I don't want to _interact_ with people wanting to join **`@dwyl`** ... 👎 
But rather because I want to streamline the expansion of our community and "network". 🚀 
And keep _track_ of who has joined when. 📝

**Comment by nelsonic** [comment]
Coming soon: https://gitbu.fly.dev/ 🔜 🧑‍💻 ⏳ 
![image](https://user-images.githubusercontent.com/194400/194248594-e799860e-6348-4fea-bfde-c010633e4043.png)

**Comment by nelsonic** [comment]
https://github.com/dwyl/start-here/issues/229 is an example of the kind of issue we've had a _lot_ of:
![image](https://user-images.githubusercontent.com/194400/194822493-f454be93-d007-4efb-8340-2d7d4c26da14.png)

I'm all **`for`** people joining the **`dwyl`** community. 🎉 
And making their membership **`public`**:  https://github.com/rtewari056
![Rohit-github-profile](https://user-images.githubusercontent.com/194400/194822905-30101772-497b-4a2b-ab5f-15b829f572b2.png)

I just don't want to have to waste my _time_ having to _manually_ add people who aren't ever going to _actually_ contribute to any projects and are just "collecting org badges" ... 🙄 

Need to _automate_ this! 🤖 

And then make it _much_ clearer _exactly_ how to contribute to the Org/Product. 💭

**Comment by vedant-z** [comment]
Hey @nelsonic is this issue fixed?

**Comment by ashwetpandoor-creator** [comment]
Mere ko Instagram id hack karaneka hai kaise kare
